name: "Do Things"
on:
  workflow_dispatch:

jobs:
  thing:
    name: Do Something
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: port
        uses: melusina-org/setup-macports@v1
      - name: port install freetype
        run: |
          port -d sync
          port install freetype
