name: "Do Things"
on:
  workflow_dispatch:

jobs:
  thing:
    name: Do Something
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: port
        uses: melusina-org/setup-macports@v1
        with:
          parameters: '.github/macports/macports.yaml'
      - name: test
        run: |
          port
